
[[package]]
org = "samith"
name = "BXmlConverter"
version = "1.0.0"
dependencies = [
	{org = "ballerina", name = "file"},
	{org = "ballerina", name = "graphql"},
	{org = "ballerina", name = "io"},
	{org = "ballerina", name = "jballerina.java"},
	{org = "ballerina", name = "lang.regexp"},
	{org = "ballerina", name = "test"},
	{org = "ballerinax", name = "mongodb"}
]
modules = [
	{org = "xlibb", packageName = "graphql_schema_registry", moduleName = "graphql_schema_registry"},
	{org = "xlibb", packageName = "graphql_schema_registry", moduleName = "graphql_schema_registry.datasource"},
	{org = "xlibb", packageName = "graphql_schema_registry", moduleName = "graphql_schema_registry.differ"},
	{org = "xlibb", packageName = "graphql_schema_registry", moduleName = "graphql_schema_registry.exporter"},
	{org = "xlibb", packageName = "graphql_schema_registry", moduleName = "graphql_schema_registry.merger"},
	{org = "xlibb", packageName = "graphql_schema_registry", moduleName = "graphql_schema_registry.parser"},
	{org = "xlibb", packageName = "graphql_schema_registry", moduleName = "graphql_schema_registry.registry"}
]