[package]
org = "samith"
name = "yaml_package"
version = "0.1.0"
distribution = "2201.8.4"

[build-options]
observabilityIncluded = true

[[platform.java17.dependency]]
groupId = "org.yaml"
artifactId = "snakeyaml"
version = "1.25"
