[package]
org = "samith"
name = "ballerina.omelement.intergration"
version = "0.1.0"
distribution = "2201.8.4"


[[platform.java17.dependency]]
groupId = "org.samith"
artifactId = "omelement-native"
version = "0.1.0"
path = "../native/build/libs/omelement-native-0.1.0-SNAPSHOT.jar"