[package]
org = "samith"
name = "ballerina.omelement.intergration"
# authors = ["samithkavishke"]
# repository = "https://github.com/samithkavishke/OMElement-Bal-Intergration"
version = "0.1.0"
distribution = "2201.8.4"

[[platform.java17.dependency]]
groupId = "org.samith"
artifactId = "omelement-native"
version = "0.1.0"
path = "../native/build/libs/omelement-native-0.1.0-SNAPSHOT.jar"

[[platform.java17.dependency]]
groupId = "org.apache.synapse"
artifactId = "synapse-core"
version = "3.0.2"
path = "../native/lib/synapse-core-3.0.2.jar"    

[[platform.java17.dependency]]
groupId = "org.apache.axis2"
artifactId = "adb"
version = "3.0.2"
path = "../native/lib/axis2-adb-1.7.9.jar"  

[[platform.java17.dependency]]
groupId = "org.apache.axis2"
artifactId = "clustering"
version = "3.0.2"
path = "../native/lib/axis2-clustering-1.7.9.jar"  

[[platform.java17.dependency]]
groupId = "org.apache.axis2"
artifactId = "kernel"
version = "3.0.2"
path = "../native/lib/axis2-kernel-1.7.9.jar"  

[[platform.java17.dependency]]
groupId = "org.apache.axis2"
artifactId = "transport-base"
version = "3.0.2"
path = "../native/lib/axis2-transport-base-1.7.9.jar" 

[[platform.java17.dependency]]
groupId = "org.apache.axis2"
artifactId = "transport-http"
version = "3.0.2"
path = "../native/lib/axis2-transport-http-1.7.9.jar"  

[[platform.java17.dependency]]
groupId = "org.apache.neethi"
artifactId = "neethi"
version = "3.0.3"
path = "../native/lib/neethi-3.0.3.jar" 

[[platform.java17.dependency]]
groupId = "org.apache.synapse"
artifactId = "commons"
version = "3.0.2"
path = "../native/lib/synapse-commons-3.0.2.jar"  

[[platform.java17.dependency]]
groupId = "org.apache.synapse"
artifactId = "tasks"
version = "3.0.2"
path = "../native/lib/synapse-tasks-3.0.2.jar" 